// <auto-generated />
using Gooios.PaymentService.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Gooios.PaymentService.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20180317140532_InitDb")]
    partial class InitDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("Gooios.PaymentService.Domains.Aggregates.WeChatPaymentNotifyMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnName("created_on");

                    b.Property<string>("MessageContent")
                        .IsRequired()
                        .HasColumnName("message_content");

                    b.Property<string>("NotifyApiName")
                        .IsRequired()
                        .HasColumnName("notify_api_name")
                        .HasMaxLength(80);

                    b.HasKey("Id");

                    b.ToTable("wechat_payment_notify_messages");
                });
#pragma warning restore 612, 618
        }
    }
}
