// <auto-generated />
using Gooios.VerificationService.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Gooios.VerificationService.Migrations
{
    [DbContext(typeof(VerificationDbContext))]
    [Migration("20180118004532_InitDb")]
    partial class InitDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("Gooios.VerificationService.Domain.Aggregates.Verification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<int>("BizCode")
                        .HasColumnName("biz_code");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnName("code")
                        .HasMaxLength(80);

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnName("created_on");

                    b.Property<DateTime>("ExpiredOn")
                        .HasColumnName("expired_on");

                    b.Property<bool>("IsSuspend")
                        .HasColumnName("is_suspend");

                    b.Property<bool>("IsUsed")
                        .HasColumnName("is_used");

                    b.Property<DateTime>("LastUpdOn")
                        .HasColumnName("last_upd_on");

                    b.Property<string>("To")
                        .IsRequired()
                        .HasColumnName("to")
                        .HasMaxLength(80);

                    b.HasKey("Id");

                    b.ToTable("verifications");
                });
#pragma warning restore 612, 618
        }
    }
}
