// <auto-generated />
using Gooios.OrganizationService.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Gooios.OrganizationService.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("Gooios.OrganizationService.Domains.Aggregates.Organization", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasColumnName("area")
                        .HasMaxLength(20);

                    b.Property<string>("CertificateNo")
                        .IsRequired()
                        .HasColumnName("certificate_no")
                        .HasMaxLength(80);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnName("city")
                        .HasMaxLength(20);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnName("created_by")
                        .HasMaxLength(80);

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnName("created_on");

                    b.Property<string>("CustomServicePhone")
                        .IsRequired()
                        .HasColumnName("custom_service_phone")
                        .HasMaxLength(80);

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnName("full_name")
                        .HasMaxLength(200);

                    b.Property<string>("Introduction")
                        .HasColumnName("introduction")
                        .HasMaxLength(4000);

                    b.Property<bool>("IsSuspend")
                        .HasColumnName("is_suspend");

                    b.Property<string>("LastUpdBy")
                        .HasColumnName("updated_by")
                        .HasMaxLength(80);

                    b.Property<DateTime?>("LastUpdOn")
                        .HasColumnName("updated_on");

                    b.Property<double>("Latitude")
                        .HasColumnName("latitude");

                    b.Property<string>("LogoImageId")
                        .IsRequired()
                        .HasColumnName("logo_image_id")
                        .HasMaxLength(200);

                    b.Property<double>("Longitude")
                        .HasColumnName("longitude");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnName("phone")
                        .HasMaxLength(80);

                    b.Property<string>("Postcode")
                        .IsRequired()
                        .HasColumnName("post_code")
                        .HasMaxLength(20);

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnName("province")
                        .HasMaxLength(20);

                    b.Property<string>("ShortName")
                        .HasColumnName("short_name")
                        .HasMaxLength(80);

                    b.Property<string>("StreetAddress")
                        .IsRequired()
                        .HasColumnName("street_address")
                        .HasMaxLength(200);

                    b.HasKey("Id");

                    b.ToTable("organizations");
                });
#pragma warning restore 612, 618
        }
    }
}
